### ISSUE TITLE
support for `MBCn`

### ISSUE THREAD

**Issue by kongdd** [saedoquililongo/climQMBC#3]
Hi @saedoquililongo,  

MBCn is a more advanced quantile mapping function, which is on the top of `QDM`. 
Do you have any plan to support `MBCn`?

https://rdrr.io/cran/MBC/man/MBCn.html

Thanks
Dongdong

**Comment by saedoquililongo** [comment]
Hi Dongdong,

Although they are an interesting topic, in the **short term** we have no plans related to multivariate methods.

Regards,
Sebastián Aedo Q.
